apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: backend
          image: '{{ .Values.ghcr }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

