services:
  server:
    build: ./server
    networks:
      - local-shared-network
    ports:
      - '3000:3000'
      - '9229:9229'
    env_file:
      - path: ./server/db.env
        required: true
    volumes:
      - ./server:/app

  client:
    build: ./client
    networks:
      - local-shared-network
    ports:
      - '5173:80'
    volumes:
      - ./client:/app
    depends_on:
      - server

networks:
  local-shared-network:
    external: true
