name: 'Get short sha'
description: Getting the short sha from the commit'
inputs:
  full-sha:  # id of input
    description: 'Full sha'
    required: true
outputs:
  short-sha:
    description: "Returned short sha"
    value: ${{ steps.short-commit-sha.outputs.short-sha }}
runs:
  using: "composite"
  steps:
    - name: Get short commit sha
      id: short-commit-sha
      run: echo "short-sha=$(git rev-parse --short ) $FULL_SHA" >> $GITHUB_OUTPUT
      shell: bash
      env:
        FULL_SHA: ${{ inputs.full-sha }}

