apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.appLabel }}
    spec:
      containers:
        - name: backend
          image: '{{  .Values.global.ghcr }}/{{  .Values.backend.image.repository }}:{{  .Values.backend.image.tag }}'
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.backend.configMapName }}
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.backend.configMapName }}
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secretName }}
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.backend.configMapName }}
                  key: DB_PORT
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.backend.secretName }}
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

