apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-{{ .Values.namespace }}-secrets
  namespace: {{ .Values.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]