apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
    spec:
      serviceAccount: {{ .Values.serviceAccount }}
      containers:
        - name: front-end
          image: '{{ .Values.ghcr }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: API_URL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          
