namespace: dev

global:
  ghcr: ghcr.io/raneric

backend:
  name: api-deployment
  appLabel: backend-api
  replicaCount: 2

  image:
    repository: booking-api
    tag: 'latest' # default value, overrode with short SHA in CI
    pullPolicy: IfNotPresent

  containerPort: 3000

  configMapName: api-cm
  secretName: api-secrets
  serviceName: client-svc

  resources:
    requests:
      memory: '128Mi'
      cpu: '250m'
    limits:
      memory: '256Mi'
      cpu: '500m'

frontend:
  name: front-deployment
  appLabel: react-app
  replicaCount: 2

  image:
    repository: react-front
    tag: 'latest'
    pullPolicy: IfNotPresent

  containerPort: 80

  configMapName: client-cm
  serviceName: client-svc

  resources:
    requests:
      memory: '128Mi'
      cpu: '250m'
    limits:
      memory: '256Mi'
      cpu: '500m'
