name: booking-api-app-build
run-name: Build and Push Docker Image for booking-api-app
on:
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: install dep
        run: |
          cd server
          npm install

      - name: run-test
        run: |
          cd server
          npm test

  build-push-api-image:
    needs: [unit-test]
    uses: ./.github/workflows/build-login-push-image.yml
    with:
      image-repo: 'booking-api'
      docker-context: './server'
      docker-file: './server/Dockerfile'
    secrets:
      token: ${{ secrets.PAT_SECRET }}
