name: booking-api-app-build
run-name: Build and Push Docker Image for booking-api-app
on:
  workflow_dispatch:
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: install dep
        run: |
          cd server
          npm install

      - name: run-test
        run: |
          cd server
          npm test

  check-deps-vulnerability:
    needs: [unit-test]
    uses: ./.github/workflows/vulnerabilities-checker.yml
    with:
      working-directory: "server"
      source: "api-ci"

  build-push-api-image:
    needs: [check-deps-vulnerability]
    uses: ./.github/workflows/build-login-push-image.yml
    with:
      image-repo: "booking-api"
      docker-context: "./server"
      docker-file: "./server/Dockerfile"
      build-args: |
        FRONTEND_HOST=${{ vars.FRONTEND_HOST }}
    secrets:
      token: ${{ secrets.PAT_SECRET }}
