name: auto-deps-update
run-name: Login to a container registry, build and push image
on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      should-run-unit-test:
        required: false
        type: boolean
        default: false
      node-version:
        required: false
        type: string
        default: '24'

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run update
        working-directory: ${{ inputs.working-dir }}
        run: |
          echo "----------Running git diff before------------"
          git diff
          echo "----------------------------------------"
          npm audit fix || true
          echo "----------Running git diff after------------"
          git diff
          echo "-----------------------------------"
      - name: Check for changes
        working-directory: ${{ inputs.working-dir }}
        id: changes
        run: |
          echo "----------Running git diff------------"
          git diff
          echo "----------Running git diff------------"
          if git diff --quiet; then
            echo "is_deps_updated=false" >> $GITHUB_OUTPUT
          else
            echo "is_deps_updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Run unit test
        working-directory: ${{ inputs.working-dir }}
        if: inputs.should-run-unit-test == true && steps.changes.outputs.is_deps_updated == 'true'
        run: |
          npm install
          npm test

      - name: Run build
        working-directory: ${{ inputs.working-dir }}
        if: steps.changes.outputs.is_deps_updated == 'true'
        run: |
          npm run build

      - name: Commit changes
        if: steps.changes.outputs.is_deps_updated == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b auto-dep-fix
          git add .
          git commit -m "chore: auto fix vulnerabilities"
          git push origin auto-dep-fix

      - name: Create PR
        if: steps.changes.outputs.is_deps_updated == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          branch: auto-dep-fix
          title: 'Auto dependency fix'
          body: 'Automated npm audit fix'
