name: auto-deps-check
run-name: Scheduled dependency vulnerability check
on:
  workflow_dispatch:

jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

  check-api-deps-vulnerability:
    uses: ./.github/workflows/vulnerabilities-checker.yml
    with:
      working-directory: 'server'
      source: 'auto-check'

  auto-update-api-deps-if-vulnerability-found:
    uses: ./.github/workflows/auto-deps-update.yml
    needs: check-api-deps-vulnerability
    if: needs.check-api-deps-vulnerability.outputs.has_vulnerability == true
    with:
      working-dir: 'server'
      should-run-unit-test: true

  check-react-deps-vulnerability:
    uses: ./.github/workflows/vulnerabilities-checker.yml
    with:
      working-directory: 'client'
      source: 'auto-check'

  auto-update-front-deps-if-vulnerability-found:
    uses: ./.github/workflows/auto-deps-update.yml
    needs: check-react-deps-vulnerability
    if: needs.check-react-deps-vulnerability.outputs.has_vulnerability == true
    with:
      working-dir: 'client'
