name: check-helm-file-on-push
run-name: Check helm file when on pus
on:
  push:
    paths:
      - 'helm/**'
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

  test-helm-lint-on-backend:
    needs: [checkout-job]
    uses: ./.github/workflows/helm-lint.yml
    with:
      helm-folder: 'helm/backend/'

  test-helm-lint-on-frontend:
    needs: [checkout-job]
    uses: ./.github/workflows/helm-lint.yml
    with:
      helm-folder: 'helm/frontend/'
