name: build-login-push-image
run-name: Login to a container registry, build and push image
on:
  workflow_call:
    inputs:
      image-repo:
        required: true
        type: string
      docker-context:
        required: true
        type: string
      docker-file:
        required: true
        type: string
jobs:
  containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: jnb.ocir.io
          username: ${{ secrets.TENANCY }}/${{ secrets.EMAIL }}
          password: ${{ secrets.OCI_REGISTRY_PWD }}
      - name: get commist short sha
        id: short-sha-step
        uses: ./.github/actions/get-short-sha-action/
        with:
          full-sha: ${{ github.sha }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.docker-context }}
          file: ${{ inputs.docker-file }}
          push: true
          tags: ${{ secrets.OCI_REGION }}/${{ secrets.TENANCY }}/${{ inputs.image-repo }}:${{ steps.short-sha-step.outputs.short-sha }}
      
