name: booking-react-app-build
run-name: Build and Push Docker Image for booking-react-app
on:
  push:
    paths:
      - 'client/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: jnb.ocir.io
          username: ${{ secrets.TENANCY }}/${{ secrets.EMAIL }}
          password: ${{ secrets.OCI_REGISTRY_PWD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ vars.OCI_REGION }}/${{ secrets.TENANCY }}/${{ vars.REACT_APP_IMAGE_REPO }}:latest
