name: booking-react-app-build
run-name: Build and Push Docker Image for booking-react-app
on:
  workflow_dispatch:
jobs:
  build-push-react-app-image:
    uses: ./.github/workflows/build-login-push-image.yml
    with:
      image-repo: 'react-front'
      docker-context: './client'
      docker-file: './client/Dockerfile'
    secrets:
      token: ${{ secrets.PAT_SECRET }}
