name: helm-upgrade
run-name: Run helm upgrade with the provided args

on:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string
      helm-folder:
        required: true
        type: string
      release-name:
        required: true
        type: string

jobs:
  helm-lint:
    name: Run helm lint command to check helm files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: get commit short sha
        id: short-sha-step
        uses: ./.github/actions/get-short-sha-action/
        with:
          full-sha: ${{ github.sha }}

      - name: Run helm lint
        run: |
          helm upgrade ${{ inputs.release-name }} ./${{ inputs.helm-folder }} \
          set image.tag=${{ steps.short-sha-step.outputs.short-sha }}
