name: manual test workfolw

on:
  workflow_dispatch: 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "$DATA_TEST"
        env:
          DATA_TEST: ${{ github.job }}
