name: manual-workflow
run-name: Manual workflow for test purpose
on:
  workflow_dispatch:

jobs:
  test-short-sha:
    runs-on: ubuntu-latest
    outputs:
      short-sha: ${{ steps.custom-sha.outputs.short-sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: test custom action
        id: custom-sha
        uses: ./.github/actions/get-short-sha-action/
        with:
          full-sha: ${{ github.sha }}
      - name: Set short-sha output
        run: echo "short-sha=${{ steps.custom-sha.outputs.short-sha }}" >> $GITHUB_OUTPUT

  test-vulnerability-server:
    uses: ./.github/workflows/vulnerabilities-checker.yml
    with:
      working-directory: 'server'

  test-vulnerability-client:
    uses: ./.github/workflows/vulnerabilities-checker.yml
    with:
      working-directory: 'client'

  test-helm-lint-on-backend:
    needs: [test-short-sha]
    uses: ./.github/workflows/helm-install.yml
    with:
      commit-sha: ${{ needs.test-short-sha.outputs.short-sha }}
      helm-folder: 'helm/backend/'

  test-helm-lint-on-frontend:
    needs: [test-short-sha]
    uses: ./.github/workflows/helm-install.yml
    with:
      commit-sha: ${{ needs.test-short-sha.outputs.short-sha }}
      helm-folder: 'helm/frontend/'
