name: manual test workfolw

on:
  workflow_dispatch: 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: git rev-parse --short ${{ github.sha }}
        env:
          DATA_TEST: ${{ github.sha }}
