name: manual test workfolw

on:
  workflow_dispatch: 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: test custom action
        id: custom-sha
        uses: ./.github/actions/get-short-sha-action/
        with:
          full-sha: ${{ github.sha }}
      - name: test data
        run: echo $FULL_SHA
